version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/projects/pharmacare_vue
    overwrite: true

permissions:
  - object: /var/www/html/projects/pharmacare_vue
    owner: ubuntu
    group: www-data
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: ubuntu